version: "3.9"
services:
    database:
        image: postgres
        env_file:
            - postgres.env
    backend:
        depends_on:
            - database
        build: ./backend
        ports:
            - 5000:5000
        volumes:
            - ./backend:/app
        env_file:
            - postgres.env
        environment:
            - SECRET_KEY=dev
            - DATABASE_HOST=database
            - DATABASE_PORT=5432
            - ORIGIN=http://localhost:4200
    frontend:
        depends_on:
            - backend
        build: ./frontend
        ports:
            - 4200:4200
            - 49153:49153
        volumes:
            - ./frontend:/app
            - /app/node_modules
